docs_dir: 'docsource'
site_dir: 'docs'
site_name: ADAM
nav:
  - Intro:
      - 'requirements.md'
      - Installation: 'install.md'
      - 'help.md'
  - App:
      - 'app/firstRun.md'
      - Setup:
          - 'app/setup/index.md'
          - 'app/setup/permissions.md'
      - Settings:
          - 'app/settings/application.md'
          - 'app/settings/authentication.md'
      - Users:
          - 'app/users/search.md'
      - Groups:
          - 'app/groups/search.md'

theme:
  name: material
  favicon: images/small-logo.png
  logo: images/small-logo.png
  features:
    - instant
  palette:
    primary: blue grey
    accent: indigo

#repo_name: jacobsen9026/AD-Accounts-Manager
#repo_url: https://github.com/jacobsen9026/AD-Accounts-Manager

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jacobsen9026

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true